version: "3"

services:
 nginx:
  container_name: nginx
  build: ./requirements/nginx/ 
  #image: nginx
  networks:
        - private_netnetwork
  restart: unless-stopped
  ports:
          - "8080:443"
  volumes:
           - wp_data:/var/www/html
  depends_on:
      - wordpress
 wordpress:
  container_name: wordpress
  build: ./requirements/wordpress/ 
  #image: wordpress:php8.2-fpm-alpine
  networks:
        - private_netnetwork
  ports:
        - "9000:9000"
  volumes:
          - wp_data:/var/www/html
volumes:
 wp_data:
  name: nginx
  driver: local
networks:
 private_netnetwork: