version: "3"

services:
 nginx:
  container_name: nginx
  build: ./requirements/nginx/ 
  #image: nginx
  networks:
        - private_network
  restart: unless-stopped
  ports:
          - "8100:443"
  volumes:
           - wp_data:/var/www/html
  depends_on:
      - wordpress
 wordpress:
  container_name: wordpress
  build: ./requirements/wordpress/ 
  #image: wordpress:php8.2-fpm-alpine
  networks:
        - private_network
  volumes:
          - wp_data:/var/www/html
  depends_on:
   - mariadb
 mariadb:
  container_name: mariadb
  build: ./requirements/mariadb/ 
  #image: mariadb
  networks:
   - private_network
  restart: always
volumes:
 wp_data:
  name: nginx
  driver: local
 db_data:
  name: maria
  driver: local
networks:
 private_network: