version: "3.6"

services:
 wordpress:
  container_name: wordpress
  build: ./requirements/wordpress/ 
  #image: wordpress:php8.2-fpm-alpine
  restart: always
  networks:
        - private_net
  ports:
        - "9000:9000"
  volumes:
          - wp_data:/var/www/html
  env_file:
      - .env
  depends_on:
      - mariadb
 mariadb:
  container_name: mariadb
  build: ./requirements/mariadb/ 
  #image: mariadb
  networks:
        - private_net
  restart: always
  ports:
        - "3306:3306"
  env_file:
      - .env
  volumes:
     - db_data:/var/lib/mysql
 nginx:
  container_name: nginx
  build: ./requirements/nginx/ 
  #image: nginx
  networks:
        - private_net
  restart: unless-stopped
  ports:
          - "443:443"
  volumes:
           - wp_data:/var/www/html
  depends_on:
      - wordpress
volumes:
 wp_data:
  name: wordpress
  driver: local
  driver_opts:
          device: /home/zouazahr/data/wp
          o: bind
          type: none
 db_data:
  name: mariadb
  driver: local
  driver_opts:
          device: /home/zouazahr/data/db
          o: bind
          type: none

networks:
 private_net: